### ISSUE TITLE
Make deployable on Heroku

### ISSUE THREAD

**Issue by patcon** [pol-is-trial-balloon/polis#10]
Re-ticketed from https://github.com/pol-is/polis-deploy/issues/8#issuecomment-612927970

> A proposal:
>
> 2. ...meet a set of requirements
> iv. run on heroku?

cc: @crkrenn

**Comment by crkrenn** [comment]
A question for @metasoarous: is pol.is the site still run on heroku?

**Comment by patcon** [comment]
Can't speak authoritatively, but until you hear from Chris: https://builtwith.com/pol.is says maybe? found signature for content delivery through "heroku vegur proxy" :)

**Comment by patcon** [comment]
Related: https://github.com/pol-is/polis-deploy/issues/8#issuecomment-616248802

#todo move this to `pol-is/polisServer`

**Comment by patcon** [comment]
Closing in favour of issue cross-reffed above
