### ISSUE TITLE
Ensure merged history is easily navigable

### ISSUE THREAD

**Issue by patcon** [pol-is-trial-balloon/polis#3]
Re-ticketed from https://github.com/pol-is/polis-issues/issues/128#issuecomment-611537979, https://github.com/pol-is-trial-balloon/polisCode/pull/1#issuecomment-611731589

@crkrenn raised a good point that with all the files moving, git history acts unexpectedly when using `git log`, as history doesn't follow file moves/renames by default.

He suggested documenting this somewhere.  An alternative is we could just roll a solution into a setup step (`make setup` or `npm setup` or whatever), then it can perhaps be more of a footnote.

Related:

- StackOverflow: [Why does git log not default to git log --follow?](https://stackoverflow.com/a/12150977)
- StackOverflow: [Storing git config as part of the repository](https://stackoverflow.com/a/18330114)

**Comment by crkrenn** [comment]
I'm not sure that we can hide the "--follow" issue behind configuration. It was designed for files, and I'm not sure if it behaves appropriately for directories (though at least it does not throw errors). 

Because of the reorg, it is important to keep the "xLegacyPolisXXX" repos around, so that the evolution of the code structure and directory subtrees can be examined. 

+1 on an alias for "log --follow". "logf" maybe?

```
cd polisMath
git log > log1.txt
git log bin > log2.txt
wc -l log?.txt
    5662 log1.txt
     133 log2.txt
```

**Comment by patcon** [comment]
> I'm not sure if it behaves appropriately for directories

As I understand, `git log --follow` doesn't ever work on directories once they're moved, nevermind whether using flag or config. (This makes sense to me, since dirs aren't first-class objects in git).

```
$ git clone pol-is/polisMath
$ cd polisMath
$ git log --follow src | head -5
dfe233e - (HEAD -> master, origin/master, origin/HEAD) final export fixes (10 months ago) <Christopher T Small>
3a2e19d - replace korma with honeysql (joy) (1 year, 2 months ago) <Christopher T Small>
2289689 - clean up config/->boolean method (1 year, 2 months ago) <Christopher T Small>
5f705cb - finish adding database-ignore-ssl option (1 year, 2 months ago) <Christopher T Small>
d303f8d - ignore dk.active.docjure (breaking things) (1 year, 2 months ago) <Christopher T Small>

$ git mv src src2
$ git commit -m "foo"
$ git log --follow src2 | head -5
2c856a9 - (HEAD -> master) foo (7 seconds ago) <Patrick Connolly>%
```

So if I'm right about that, I'm not sure the rationale for a `logf` alias -- the gitconfig makes it as good as it will ever be, so no need to ever use an alias cmd, right?

**Comment by patcon** [comment]
New PR against `dev`: https://github.com/pol-is/polisServer/pull/245
