### ISSUE TITLE
Create a local docker dev environment

### ISSUE THREAD

**Issue by patcon** [pol-is-trial-balloon/polis#8]
Re-ticketed from: https://github.com/pol-is/polis-deploy/issues/8#issuecomment-612927970

> i. run on localhost in docker containers
> ii. run on localhost with compiled static content for clientParticipation and clientAdmin

Does this feel like a unit of work @crkrenn?

Related: https://github.com/pol-is/polis-issues/issues/125, https://github.com/pol-is/polis-deploy/issues/4

## Summary

- Working code on `docker-dev` feature branch: https://github.com/patcon/polisServer/tree/docker-dev
- Diff from `monorepo` branch (future merge): https://github.com/pol-is-trial-balloon/polis/compare/monorepo...patcon:docker-dev?w=1
- Features:
  - 10-15min initial build time on high-speed connnection (faster after)
  - working `report` component for report generation
  - `math` component working properly and communicating
  - multi-stage docker builds for `client-*` UI components
  - minimal changes to get full docker dev environment working
  - tested only with `docker-machine`, built on remote digitalocean cloud instance

**Comment by crkrenn** [comment]
+1 and, fortunately, it is well on its way!

**Comment by patcon** [comment]
Been tinkering with this the past few weeks too (not committed to any of my code being the merged one)

My in-progress docker exploration here: https://github.com/pol-is-trial-balloon/polisCode/compare/monorepo...patcon:docker-dev

- tried proxying all requests through nginx at first, but realized it would be quite a divergence from the official approach of polisServer proxying through to fileserver.js, so was then trying to get a minimal variation of the official way working
- currently spins up, but only clientAdmin works (serving through ngxinx). clientParticipation doesn't work due to the way frontend code can't be served directly, but needs to proxy through polisServer in order to have preloaded data replaced into the request
- using multi-stage docker build for `fileServer/` and pre-compilation of frontend UI.
  - working on getting `*.headersJson` generating for local copy deploy (scp/s3 deploy doesn't make sense for local deploy to directory that's best for docker setup)

**Comment by patcon** [comment]
Related: https://github.com/pol-is/polis-issues/issues/125

**Comment by crkrenn** [comment]
scp might be good enough for local. scp file1.txt file2.txt works as expected and doesn't require authentication.

**Comment by patcon** [comment]
Thought the same thing, but [`node-scp2`](https://github.com/spmjs/node-scp2) is a pure js implementation, and not a resurfacing of the `scp` command. It doesn't seem to support that in my experimentation -- a string as the first arg means that a remote config object is then expected for second arg, and vice versa:

```js
// this doesn't work
client.scp('./file1.txt', './file2.txt', function(err) {
  // ...
})
```

maybe i was doing it wrong, so happy to be shown otherwise. (a new "upload" strategy for local copy seems to be about 10 new lines, that i already have sorted)

**Comment by crkrenn** [comment]
No objection. Just some trivia from my command line days moving files around.


Chris Krenn
Lawrence Livermore National Laboratory
Krenn1@llnl.gov<mailto:Krenn1@llnl.gov>
925-423-8636
--------------------------------------------
Q: Why is this email [hopefully] five sentences or less?
A: http://five.sentenc.es

**Comment by patcon** [comment]
Ok, have a minimal changeset that builds a 99% fully-functional instance via `docker-compose up`. I've been testing it via `docker-machine` and Digital Ocean, since I don't have a beefy enough computer to run docker locally.

Comparison with pending `monorepo` branch: https://github.com/pol-is-trial-balloon/polis/compare/monorepo...patcon:docker-dev

- See readme additions for instructions.
- The GIT_HASH envvar was the quickest way to pass it into the container script even though there was no git repo in subdir. We could do other things to ditch this, but I tried not to change for now.
- the copious amounts of dependencies mean that sometimes fetches fail, but re-running our `docker-compose up` command eventually completes.
- tried to make as few changes as possible to get this working
- leaned on https://ey.pdis.nat.gov.tw/shared/jBu2tBuLKYrTofBMEjf1PyxGMFTbu1QAwgR5GyUppGp for guidance (h/t @urakagi! 🙌 )

@crkrenn curious your thoughts, and whether this looks consolidatable with your efforts? (is there a link to your pending feature branch btw?)

cc: @metasoarous @ballpointpenguin

**Comment by crkrenn** [comment]
Ignore my previous comment. I’m looking forward to giving this a try.

**Comment by crkrenn** [comment]
I gave it a try this morning on os x and ubuntu 18. On both, I had problems the first time through with a timeout while downloading alpine linux, but trying again solved that problem. 

Is it possible to remove the dependence on the GIT_HASH definition? It definitely is needed but is non standard. 

Both are still building. More after walking my dog.

**Comment by crkrenn** [comment]
* I confirmed that it is up and running on ubuntu. Great job! 
     * After building, `docker-compose down` and `docker-compose up` work properly. 
     * It built successfully on OS X, but doesn't automatically forward from `ip:5000` to `ip:5000/home`. Going directly to `ip:5000/home` does work. 
* +1 on a pull request to polisServer/dev after monorepo is merged in.
* I will migrate my work in progress to hang off this branch. Goals include:
     1. A faster build if possible.
          1. Evaluation whether `node client-admin` and `node client-participation` have advantages over `file-server`
     1. Deployment on aws
     1. Compile time customization of more text and privacy policies

**Comment by patcon** [comment]
Cool! Thanks for trying it out @crkrenn! I think I may have pushed a few small commits since you built, which (1) fixes a problem with the `client-admin` build failing intermittently on postinstall for `core-js` or `radium`, and (2) fixes report and data export features that were broken in non-obvious ways.

> Is it possible to remove the dependence on the GIT_HASH definition?

heh, yep, two approaches to mitigate need for that:
(1) do some odd stuff with moving the docker "context" up a level to root, and then have `.git/` dir copied into the container, so tjhe git hash can be determined directly, or
(2) remove knowledge/need of git hash from app setup (e.g. removing from cache dir name and striking hash from build number strings in live website)

I thought the above might be a bigger convo with some consultation of trade-offs, so thought that could be a separate convo/PR after merging MVP working build into `dev`. Would that work?

> Going directly to ip:5000/home does work.

Hm. I'm not actually accessing nginx on that port. I had it set up to serve on port 80. Though now that you mention it, perhaps that's not working because something else is running on your 80? If so, might be better to use need a nonstandard port by default.

[diagram of architecture](https://www.draw.io/?#R7VlNj5swEP01OabCNgRybTbdPbRSq6zU7tEFB9wSjIwJpL%2B%2BJpgY4mQ3jRJgpe5hxTx%2Fv5l5DM4ELTblI8dp9IUFJJ5AKygn6GEC4Ry58n8F7GrAnlk1EHIa1BDQwIr%2BIQpsuuU0IFmno2AsFjTtgj5LEuKLDoY5Z0W325rF3VVTHBIDWPk4NtHvNBBRjXqOpfEnQsOoWRlYquUn9n%2BHnOWJWm8C0Xr%2FVzdvcDOX6p9FOGBFC0LLCVpwxkT9tCkXJK6obWirx30603rYNyeJuGTAdL7yim%2B5i8ETCkp%2FUTyvnqeHzYldQwgJJD%2FKZFxELGQJjpca%2Fbg%2FNKmmtaSl%2B3xmLJUgkOAvIsROORvngkkoEptYtZKSih%2FV8A%2BOsl7UZNXzQ9k2do2RCL5rDarMl2a%2BytDD9lYzzqRJMZexnPvkFW6aaMQ8JOKVfk7dr%2BKttYBywiNhGyL3IztwEmNBt924wyp8w0M%2F7UL5oLz4Dx5V825xnKuVkpAmpeHmrhOLiAqySvGekEImetdhZ0ncEi5I%2BeqxVevMVqGmdAJATwGFTjvQxGPUSrlGUG5OFTSoWtOYTDPC5bEGJ8yFR4RZtkkYtPskDMyuUAs%2Fl3QGipc7SQe4Sjqsu0kHulA64KikAxn54MdUnn2Kgw1NRpcQ8xP50K%2BAAPd%2FPlyUD%2Fa7zAf7XD5ICgT1aSr3wIbPC88eXV54I82LsZWYzrvMCwSHd%2B%2BVrromLHpwr31r%2F6qhXxmVe9Y1OHK6JSXwjiSgPpIadhQmh31cHzmOoagjKbaNrxMw%2BNfJzOAqZZkIOckGZ8vxLvg0AaDXV44zvCYpbQFtZTnozFuvnE4hpkXt5q8c90JNmo3qleMaybC%2FXxs6EWzrkkTo91LDvADyLM%2B85tNUgX6qVOM644TCnrrNgHdjyrz%2FGQFPs2NtRXBonsx7AceyRsgUHJwp84vRsU9Uy70zBY7qvuFzz6wEEWgCbUCm7OM68I5MSVP%2F%2BlNX2PoXNrT8Cw%3D%3D)

> I will migrate my work in progress to hang off this branch. Goals include:

Aw hey, sounds great! Am i understanding correctly that these features can become future PR's against `dev`, and you're mostly +1 to merge `docker-dev` once `monorepo` is merged?

Again, thanks for the review!

**Comment by patcon** [comment]
Woo 🎉 Got polisReport tentatively working in my `docker-dev` branch! Cherry-picked a commit mentioned here to get it working: h/t @urakagi 
https://github.com/pol-is/polisServer/issues/42#issuecomment-455447988

I'll create a PR upstream just as soon as the monorepo re-org PR https://github.com/pol-is/polisServer/pull/60 is merged. cc: @metasoarous

<img width="1418" alt="Screen Shot 2020-04-27 at 1 59 06 AM" src="https://user-images.githubusercontent.com/305339/80335478-c4cd1500-882a-11ea-9901-a6c5244370f4.png">

**Comment by crkrenn** [comment]
Very excited! I’ve never used it before.

**Comment by ballPointPenguin** [comment]
Last night I had success building the full polis with patcon's docker-dev branch, on a 6-year old Lenovo Thinkpad running Clear Linux. Built in about 10 minutes (I didn't time it.) I had a couple issues but only because I had previously existing containers with the same names, and ports in conflict. When I removed or stopped other containers and re-ran, everything worked 🙌 .
It's worth mentioning that I am blessed with Gigabit fiber at home, so perhaps that why I did not have any issues pulling and downloading all of the dependencies. I will try this also on a ChromeBook and on a Web Server that I have.

**Comment by ballPointPenguin** [comment]
I'm getting some errors with the npm install bits when running on Mac OS X just now.

**Comment by patcon** [comment]
> on Mac OS X just now

EDIT: _without_ docker, right?

You'll need to use the exact versions in the Dockerfiles (yes, different versions for different components). client-admin is especially finicky -- even the patch version seemingly matters...! Might that explain?

**Comment by patcon** [comment]
Closing this as done
